#include "write_py_module.hpp"

namespace {



}

namespace skywalker {

void write_py_module(const std::vector<InputData>& input,
                     const std::vector<OutputData>& output,
                     const char* py_module_name) {
  FILE* file = fopen(py_module_name, "w");
  fprintf(file, "# This file was automatically generated by skywalker (HAERO edition).\n\n");
  fprintf(file, "# Object is just a dynamic container that stores input/output data.\n");
  fprintf(file, "class Object(object):\n");
  fprintf(file,  "    pass\n\n");

  // Write input data.
  fprintf(file, "# Input is stored here.\n");
  fprintf(file, "input = Object()\n");
  for (auto in: input) {
  }

  // Write output data.
  fprintf(file, "# Output data is stored here.\n");
  for (auto out: output) {
  }

  fclose(file);
}

}
