#include "write_py_module.hpp"

namespace {

// Writes the given input variable to our Python module.
void write_input_var(FILE* file,
                     const std::vector<skywalker::InputData>& inputs,
                     const std::string& var_name) {
  fprintf(file, "%s = [", var_name.c_str());
  for (auto input : inputs) {
    auto var = input[var_name];
    fprintf(file, "%g, ", var);
  }
  fprintf(file, "]\n");
}

// Writes the given output variable to our Python module.
void write_output_var(FILE* file,
                      const std::vector<skywalker::OutputData>& outputs,
                      const std::string& var_name) {
  fprintf(file, "%s = [", var_name.c_str());
  for (auto output : outputs) {
    auto var = output[var_name];
    fprintf(file, "%g, ", var);
  }
  fprintf(file, "]\n");
}

}  // namespace

namespace skywalker {

void write_py_module(const std::vector<InputData>& inputs,
                     const std::vector<OutputData>& outputs,
                     const char* py_module_name) {
  FILE* file = fopen(py_module_name, "w");
  fprintf(file,
          "# This file was automatically generated by skywalker (HAERO "
          "edition).\n\n");
  fprintf(
      file,
      "# Object is just a dynamic container that stores input/output data.\n");
  fprintf(file, "class Object(object):\n");
  fprintf(file, "    pass\n\n");

  // Write input data.
  fprintf(file, "# Input is stored here.\n");
  fprintf(file, "input = Object()\n");
  write_input_var(file, inputs, "temperature");
  write_input_var(file, inputs, "pressure");
  write_input_var(file, inputs, "relative_humidity");
  write_input_var(file, inputs, "height");
  write_input_var(file, inputs, "hydrostatic_dp");
  write_input_var(file, inputs, "planetary_boundary_layer_height");

  // Write output data.
  fprintf(file, "# Output data is stored here.\n");
  write_output_var(file, outputs, "num_concs");

  fclose(file);
}

}  // namespace skywalker
