// This file is autogenerated. DO NOT EDIT DIRECTLY.
#ifndef HAERO_mam_nucleation_TEST_BRIDGE_HPP
#define HAERO_mam_nucleation_TEST_BRIDGE_HPP

#include "haero/haero.hpp"

using haero::Real;

extern "C" {

// Fortran subroutines that implement this process.
extern void ternary_nuc_merik2007_bridge(const Real t, const Real rh, const Real c2, const Real c3, Real &j_log, Real &ntot, Real &nacid, Real &namm, Real &r);

} // extern "C"

#endif
