! This file is generated by the build system. PLEASE DO NOT MODIFY IT.
! Instead, edit your config.sh file and run it with "./config.sh".

!> This module contains all parameters that are determined at build time.
module modal_aero_config

  implicit none

  public

  !> Number of vertical columns in the simulation.
  integer, parameter :: pcols = 1

  !> Number of vertical levels in the simulation.
  integer, parameter :: pver = 1

  !> Number of constituent species.
  integer, parameter :: pcnst = 35

  !> Number of tags for black-carbon aerosol species.
  integer, parameter :: nbc = 1

  !> Number of tags for primary-organic aerosol species.
  integer, parameter :: npoa = 1

  !> Number of tags for secondary-organic aerosol species.
  integer, parameter :: nsoa = 1

  !> Number of tags for secondary-organic gas species.
  integer, parameter :: nsoag = 1

end module

